language: node_js
node_js:
- '0.10'
before_script:
- npm install
- npm run test
deploy:
  provider: openshift
  user: myjc.niv@gmail.com
  password:
    secure: WED6+Jz6I/nNSs6v3B4WB8osc4hMUsovVVBWRyqwW1aX2Wq50p7Sw3gQM9GwvEnO4UZWxfZGwnJlizdwu4IhbWgqptCWZQrQ8L8WOG6k0PbaqH08JBk85c+GdKuwUw/qw2FSqzcjxafOJ/dJ0Qz3G1NjILfYEzGQJFo9p31BH6XZbt1kQOpVOrkDGnxQ4lZ0JVPWWauwMByS5LQq+vgIclF09fw+0hJLK7+/yZQ6tt/DVBdioXstEA2NYxT4W2yXZvU1zN520EwJPnM5KKyKdOv6E4218OBFZBueZ2qoAjPVnQm8+uKSTf73eE2huIHDyg265gTdSDNE/C4NAhQDa0UJFKRwqUSVp77uetrcDf0RuASMxWNRhRaMlFEjlC6msYoLu0eXKk488wOX7/DQMjyqJIB0rWjXkzb3qNHJJQKSXkd9cyHzuYquO0P8HkWwNMk7Eew7kVmzkP+iorN6y7n2tmqr5V0fFzb4VWzvcAo7PI6RhszRLA7GZ12evOyDws+ch3WKx2GKrReMfuc8AB0lPkoWUKBelH07cIy9YSS2wZG+832qjAnoz9xY0c5/94qxz4O8Bc0gX01UC82ewPTQ/+/mE4YspL6cWRfzjMbWUv+t9VbkHanqLy+1WVcrnri4F1k3Kk13PRdE7KKueQ0xPeMR/+UhyzeW7Z2BYDk=
  app: gilfoyle
  domain: jordanjs
  on:
    repo: WpgTech/gilfoyle
