language: node_js
node_js:
- '0.10'
deploy:
  provider: openshift
  user: myjc.niv@gmail.com
  password:
    secure: T/jl6r/PUIc5G0fI55SmnEn8UdpCan0KMVPkiCK7RsTtyA+N47G0q6ToNyt/Je9LiIO0KEk8+akCYn+S7ArlD2tTq++ZdfzshemaSK51q3lJ/+MhXnWXDI1mnNo7E3YMft5vORqbqPy034Zxu3e64vTDCKKmO40S4ubhyJnYkBWBr4jCLQczu37C+Jlvjl6t3vgHBtQZIQPxhwlPqhTH+9D8tTXrNd0g4wvuWJl57G83VNzp6NTE9Z5jeD95fiUmpgg9jI9YKTokZd6Vy0uZ3kyMWG/Fi43il7vaMiGh1sGDJndMD+6wuU4vVdFsHJGlu8YVteoUeEy4zMbHdETK2jiW/XKGw9EzdKpdD/eog6qcIhgFQhD8WLaPZkxD29AI0ENkybL4cj7taiIl9T71UWx2NZRZG9RHGCXEe2JLESkLWfYjUybvyaxzDchpwjRp4xMro+T3y3+Wggxt6h63uPef3mnO0t8ShLW+7lF0jLa+OXKibVpJZv4B2bT7kF9dqB4rSFtmZOdcemRjqiv2H5WuebduZ3eLQkqYQ4nZLAJz5vwscajRApkguRH30tBwUKPC8vxnyYGl3FZp+5sv/D1hxGd8NInI2J623yRl8bOqLkjeOAiUe53nM8E6IX7BUps11UJFgm+Ha9r01/n81us6pep3V3Gq9XevNpDhUY8=
  app: gilfoyle
  domain: jordanjs
  on:
    repo: WpgTech/gilfoyle
    branch: master
