deploy:
  provider: openshift
  user: myjc.niv@gmail.com
  password:
    secure: xMPY2KsJbBPN9OM/L3NKpYSGDh2EDuH6ltEQsqKq5fDFtqfNY3BAv2a1VWxvK4smIccGjrSIQpPbC0TtkBEbewFGqGDYZTAovPnP/DSCMIbf5KLo9gUKL73jRezbUEswtc8djeqC9JRsNiPyQ8c0gF1PZ2PEYvJ60TDOn5nm0vz7hJ7LPpHYsb1/Tvm8k1PW866UpNsMHEjDoVQPsiuKw12nXe4kBKujlxYFId3Q+R9TU1ohe5SIBo2gWO3YzIgfmKFkDJ8rV7zOjiZktgGA9gxOrAanYmghx7ohnOUWwUIzHSbqb3fQdtkBc7f//uFGyxXrucEw+nMTy6WxsX8E9Ii8mjrEOD4JUXlWtQPWXxAAwtl4hsD1S74POSW+kVKEAFO2c6U2f7f39HbKSaCmgVAkZMI5d0uDLU2z1iWztWk/wYSqfK79a593Ok2t52txeXwDE8zc7xkzK/TxZAmBQ5GBt5ipmDQhRw3mOth8+PuC1A/kvrcdDZtTMaMoIY3SD1Bt2CCLgzIBO+QcLsC20qKRvoueLdKqDNV7BJBdrOXWaj+RYTcZFyX8szKxVmD7yArUjAg7mTGcwuj5SsomtUVp6LKyFwpZZ2UK9XpbQSDUkNOjwT5UZxidw9XqXlINqiA5VrmkmGzcKtw9mLH9XT2znDq7IbTAlMFoot2xTcM=
  app: gilfoyle
  domain: jordanjs
  on:
    repo: WpgTech/gilfoyle
